INSERT INTO producto (codigo, nombre, descripcion) 
SELECT DISTINCT PRODUCTO_LOCAL_CODIGO, PRODUCTO_LOCAL_NOMBRE, PRODUCTO_LOCAL_DESCRIPCION
FROM gd_esquema.Maestra
WHERE PRODUCTO_LOCAL_CODIGO IS NOT NULL